

= HiveMQ 4 – Example x509 Authentication Extension

== Purpose

This HiveMQ extension authenticates MQTT clients using x509 certificates. The extension evaluates the Issuer of the provided client certificate:

* If the Issuer is `alwaystrustme`, the client is fully authorized to access all topics with all permissions.
* If the Issuer differs, the extension does not authorize the client and passes the authentication process to the next available authenticator.


== Installation

Download the release package:
```bash
wget https://github.com/guinp1n/x509-extension/releases/download/initial/x509-extension-4.32.0.zip
```

Extract the contents into the HiveMQ extensions directory:
```bash
unzip -o x509-extension-4.32.0.zip -d $HIVEMQ_HOME/extensions
```

Verify the directory structure:
```text
$HIVEMQ_HOME/extensions/x509-extension
├── LICENSE
├── hivemq-extension.xml
└── x509-extension-4.32.0.jar
```

Start HiveMQ.

== Building from Source

Clone the repository:

```bash
git clone https://github.com/guinp1n/x509-extension
cd x509-extension
```

Build the extension using Gradle:
```bash
./gradlew clean hivemqExtensionZip
```

Extract the built extension to the HiveMQ extensions directory:

```bash
unzip -o build/hivemq-extension/x509-extension-4.32.0.zip -d $HIVEMQ_HOME/extensions
```

Start HiveMQ.


== License

The HiveMQ x509 Authentication Extension is licensed under the link:LICENSE[Apache License, Version 2.0]. 🐝
